hexconfig={'version': 'v1',
 'config': {'visState': {'filters': [],
   'layers': [{'id': '58nv8uc',
     'type': 'hexagonId',
     'config': {'dataId': 'data_2',
      'label': 'h3',
      'color': [255, 153, 31],
      'columns': {'hex_id': 'h3'},
      'isVisible': True,
      'visConfig': {'opacity': 0.6,
       'colorRange': {'name': 'ColorBrewer YlOrRd-3',
        'type': 'sequential',
        'category': 'ColorBrewer',
        'colors': ['#ffeda0', '#feb24c', '#f03b20'],
        'reversed': False},
       'coverage': 0.99,
       'enable3d': True,
       'sizeRange': [25, 500],
       'coverageRange': [0, 1],
       'elevationScale': 23},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'count', 'type': 'integer'},
      'colorScale': 'quantile',
      'sizeField': {'name': 'count', 'type': 'integer'},
      'sizeScale': 'linear',
      'coverageField': None,
      'coverageScale': 'linear'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'data_2': [{'name': 'h3',
        'format': None},
       {'name': 'count', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 2.6192893401015205,
   'dragRotate': True,
   'latitude': 39.174641287987534,
   'longitude': -76.62835909426111,
   'pitch': 37.374216241015446,
   'zoom': 10.155598485242904,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}
